name: qrcode_scanner
description: A simple QRCode scanner for Android and iOS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  shared_preferences: ^2.0.17

dev_dependencies:
  blackfoot_flutter_lint: ^1.0.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true